# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Publications"
  url = "#publications"
  # url = "/publication"
  weight = 60

[[main]]
  name = "Coverage"
  url = "#coverage"
  # url = "/coverage"
  weight = 70

[[main]]
  name = "About"
  url = "#about"
  weight = 110

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 120

# [[main]]
#   name = "Posts"
#   url = "/post"
#   weight = 40


# [[main]]
#   name = "Explore"
#   url = "/explore"
#   weight = 80

# [[main]]
#   name = "Courses"
#   url = "/courses"
#   weight = 100

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Classes"
#   url = "/classes"
#   weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#   name = "CV"
#   url = "files/cv.pdf"
#   weight = 80
